[package]
name = "rsmodules"
version = "0.5.2"
authors = ["Frederik Delaere <frederik.delaere@ugent.be>"]

[dependencies]
rand = "0.3"
lazy_static = "0.2"
rhai = "0.4.0"
walkdir = "1"
bincode = "0.6.1"
rustc-serialize = "0.3.23"
users = "0.5.0"
shellexpand = "1.0.0"
regex = "0.2.1"
getopts = "0.2.14"

[[bin]]
name = "rsmodules"
path = "src/main.rs"
